#!/bin/bash
podman run \
       --interactive --rm --security-opt label=disable \
       --volume ${PWD}:/pwd \
       --volume ${HOME}/dev/guacamole/data:/data \
       --workdir /pwd quay.io/coreos/butane:release \
       --files-dir /data \
       --pretty --strict \
       config.bu > ignition.ign